### ISSUE TITLE
Ad not appearing on mobile phone app

### ISSUE THREAD

**Issue by thanksforkijijimanager** [jackm/kijiji-manager#28]
Noticed this has been happening for the last few days. Posting ad will only show on desktop/web browser and not in the smartphone app. This has happened to me in the past for short periods of time and I just assumed there might be some replication delays on Kijiji end and it would eventually show up on the app but not sure anymore. Maybe some API to upload to app needs to be updated? Just a guess :P

Thanks again

**Comment by jackm** [comment]
Could you clarify what you mean by not showing on the app? Does the ad not appear in the ad list from you "My Kijiji" profile page?

**Comment by thanksforkijijimanager** [comment]
The ads appear to be showing under "My Kijiji"
They do not appear when searching using keywords
Also noticed the postal code is not resolving to the city in the ad and I think that is why this is happening
For example...Ad should says Toronto, ON M3M1A1 instead of just M3M1A1
As mentioned, this happened in the past for max 1 day at a time (few times) and noticed the issue was resolved when postal code look-up/resolution is working correctly. 

Tried with different phones and kijiji accounts, same thing...

Thx for ur reply

**Comment by thanksforkijijimanager** [comment]
Editing the ad (no changes) and saving the ad on the mobile application seems to fix the postal issue and makes ad appear using keywords

**Comment by thanksforkijijimanager** [comment]
And it seems to have resolved itself again! Not sure why its happening but im guessing its something to do with kijiji back-end since no changes were made to the app

**Comment by thanksforkijijimanager** [comment]
![image](https://user-images.githubusercontent.com/95733587/146692584-17c9af6f-33bd-4324-b50e-0abec0d651cd.png)
Tried to edit ad using web browser and noticed the Location section looks like its missing stuff...is this normal?

**Comment by jackm** [comment]
I can confirm the same thing with regard to the location for new ads posted by kijiji-manager vs older ones. I'll have to look into what changed on the Kijiji side for ad locations.

**Comment by thanksforkijijimanager** [comment]
Thanks for confirming. I noticed the mobile application is no longer asking for a region (like Toronto, Peel, etc) and seems like it is just basing it off postal code and showing the city it is in. If you look at ads on the mobile app, they no longer show regions like it did in the past. Now it shows the city for the postal put into the ad such as Brampton instead of Mississauga/Peel Region or East York instead of York Region. I think this change is what is causing this issue.  Thanks again!

**Comment by thanksforkijijimanager** [comment]
Hey @rybodiddly 
Tried with your application too (looks awesome wow!!) and experiencing the same region/postal issues thing

**Comment by rybodiddly** [comment]
Fix submitted in [Pull Request 29](https://github.com/jackm/kijiji-manager/pull/29)

**Comment by rybodiddly** [comment]
@thanksforkijijimanager I just uploaded the patch 1hr ago. If you use my version, it is also fixed now.

**Comment by thanksforkijijimanager** [comment]
Downloaded your version 20 mins ago and still having the issue, maybe I need to update my XML?
Which line/section should I be updating and reduce postal to first 3 characters or what do I input now?

**Comment by rybodiddly** [comment]
@thanksforkijijimanager yes, the xml files need to be recreated or edited so they contain longitude and latitude coordinates.

Example of Address section of xml:
```
<ad:ad-address>
     <types:zip-code>YOUR_POSTAL_CODE</types:zip-code>
     <types:longitude>-65.1234</types:longitude>
     <types:latitude>40.3456</types:latitude>
</ad:ad-address>
```

**Comment by jackm** [comment]
PR #29 merged in to master.
